### ISSUE TITLE
Possible to use "component" in routes?

### ISSUE THREAD

**Issue by subesokun** [brandonroberts/angularjs-component-router#7]
Hi, one more question :) I was wondering if it's possible to use the new `component` also for the routes. I've forked your plunker and tried to modify the `admin.js` but no luck, it's not working. Any guess what's going wrong or is it simply not possible (or doesn't make sense at all) to use here a component instead of a directive + controller?

http://plnkr.co/edit/jJur6w9VnyzLUSimTz6a

**Comment by brandonroberts** [comment]
@subesokun it is possible to use the new `component` also for routes. I changed mine because at the time there was a conflict between the angular 1 router and the component helper in the latest rc build for angular 1.5. If you want to see examples of using the `component` for routes, see: https://github.com/petebacondarwin/ng1-component-router-demo

**Comment by subesokun** [comment]
Thanks for the pointer! Sadly the repo owner is writing that the current version of the router on npm does not work with component routes :( Maybe I've experienced the same issue as I was using the npm version. Closing this issue and I'll keep an eye on the ng1-component-router-demo
